const express = require('express')
const getCategorySections = require('../controllers/getCategorySections')
const getCountdownBanner = require('../controllers/getCountdownBanner')
const getExploreVideos = require('../controllers/getExploreVideos')
const getFeatured = require('../controllers/getFeatured')
const getFooterColumns = require('../controllers/getFooterColumns')
const getLatest = require('../controllers/getLatest')
const getLegalLinks = require('../controllers/getLegalLinks')
const getLowerLatest = require('../controllers/getLowerLatest')
const getMarkets = require('../controllers/getMarkets')
const getMostRead = require('../controllers/getMostRead')
const getNavMenus = require('../controllers/getNavMenus')
const getNewsLinks = require('../controllers/getNewsLinks')
const getOpinionItems = require('../controllers/getOpinionItems')
const getPriceRows = require('../controllers/getPriceRows')
const getSearchAssets = require('../controllers/getSearchAssets')
const getSearchNews = require('../controllers/getSearchNews')
const getSocialLinks = require('../controllers/getSocialLinks')
const getThumbnailStories = require('../controllers/getThumbnailStories')

const router = express.Router()

router.get('/category-sections', getCategorySections)
router.get('/countdown-banner', getCountdownBanner)
router.get('/explore-videos', getExploreVideos)
router.get('/featured', getFeatured)
router.get('/footer-columns', getFooterColumns)
router.get('/latest', getLatest)
router.get('/legal-links', getLegalLinks)
router.get('/lower-latest', getLowerLatest)
router.get('/markets', getMarkets)
router.get('/most-read', getMostRead)
router.get('/nav-menus', getNavMenus)
router.get('/news-links', getNewsLinks)
router.get('/opinion-items', getOpinionItems)
router.get('/price-rows', getPriceRows)
router.get('/search-assets', getSearchAssets)
router.get('/search-news', getSearchNews)
router.get('/social-links', getSocialLinks)
router.get('/thumbnail-stories', getThumbnailStories)

module.exports = router
